version: '3.6'
services:
  node:
    container_name: project_front
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3001:3001'
    volumes:
      - './src:/home/node/app'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
